### ISSUE TITLE
Using route53 with opsworks, chef 12 on windows server does not work.

### ISSUE THREAD

**Issue by nbannister85** [chef-cookbooks/route53#94]
Simple creation of record does not work, using the example code, trying to create a record in route53 from a windown server 2012 server does not work.

route53_record 'create a record' do
	name "hostnam"
	value "some private ip"
	type "A"
	ttl 60
	zone_id "zone id"
	aws_access_key_id "some key"
	aws_secret_access_key "some access key"
	overwrite true
	action :create
end

The following code produces a:  NoMethodError: undefined method `records' for nil:NilClass 
error.

I believe that in record.rb the statement zone(aws) return nil.

**Comment by bshehram** [comment]
I got it working, but it only works if you modify the build-essentials dependent cookbook (after running lets say berks vendor for your cookbook collection) and disable the default recipe to not install any packages. 

It looks like, to me, the problem is that seven_zip is requested to be installed because build-essentials is called by the route53 cookbook. The problem is that the seven_zip installation is deprecated (I get an error about how the Chef package resource method should be used) and is causing things to fail on Windows with Chef 12 in OpsWorks. 

Hopefully a fix will be issued sooner than later in the build-essentials cookbook.

**Comment by tas50** [comment]
The master branch no longer uses fog, which required build-essential for installation. This shouldn't be an issue at this point
